### ISSUE TITLE
SpringBoot健康监控

### ISSUE THREAD

**Issue by saltpi** [ourfor/Blog#95]
```yml
  - job_name: 'springboot-actuator-prometheus'
    metrics_path: '/manage/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['https://api.endeny.me/editor']
```
