### ISSUE TITLE
Fedora测试环境

### ISSUE THREAD

**Issue by saltpi** [ourfor/Blog#98]
```yml
version: "3.2"
services:
  fedora:
    container_name: fedora
    hostname: fedora
    image: fedora:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 2222:22
    command: /bin/bash
    tty: true
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/localtime:/etc/localtime:ro
```

由于容器默认命令只需完毕后会退出，所以需要添加`tty: true`
